config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  post "results", controller: :lookup, action: :results
  root "lookup#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lookup_controller.rb
class LookupController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index
  end

  def results
    begin
      @cached_response = weatherkit.cache_exists_for?(params[:address])
      @forecast = weatherkit.forecast(params[:address])
      @current = @forecast[:currentWeather].with_indifferent_access
      @nxt_days = @forecast[:forecastDaily]["days"].map(&:with_indifferent_access)

    rescue ArgumentError => e
      # this means it didn't work; temporary error... redirect to home
      flash.alert = "There was an API error, please try again."
      redirect_to action: :index and return
    end
  end

  private

  def weatherkit
    @weatherkit ||= WeatherKit.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # NOTE: I'm sure there's an algorithmic way to do this, but sometimes a
  # case statement does the job just fine.
  def direction_as_cardinal(degrees)
    case degrees.to_f
    when 0...11.25 then "North"
    when 11.25...33.75 then "North North East"
    when 33.75...56.25 then "North East"
    when 56.25...78.75 then "East North East"
    when 78.75...101.25 then "East"
    when 101.25...123.75 then "East South East"
    when 123.75...146.25 then "South East"
    when 146.25...168.75 then "South South East"
    when 168.75...191.25 then "South"
    when 191.25...213.75 then "South South West"
    when 213.75...236.25 then "South West"
    when 236.25...258.75 then "West South West"
    when 258.75...281.25 then "West"
    when 281.25...303.75 then "West North West"
    when 303.75...326.25 then "North West"
    when 326.25...348.75 then "North North West"
    end
  end

  def time_of_day(daylight)
    if daylight
      "day time"
    else
      "night time"
    end

  end

end

app/helpers/lookup_helper.rb
module LookupHelper
end

app/views/layouts/application.html.erb
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Your local forecast</title>

  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.2.0/mdb.min.css" rel="stylesheet" />
</head>

<body>
  <%= yield %>

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.2.0/mdb.min.js"></script>
</body>
</html>

app/views/lookup/index.html.erb
<style>
#intro {
  position: fixed;
  object-fit: cover;
  z-index: -1;
  right: 0;
  bottom: 0;
  min-width: 100vh;
  min-height: 100vh;
  height: 100vh;
}

#introContent {
  height: 100vh;
}
</style>

<video autoplay muted loop id="intro">
  <source src="<%= image_path("AdobeStock_197523665.webm") %>" type="video/webm" />
</video>

<div id="introContent" class="bg-image shadow-2-strong">
  <div class="mask d-flex align-items-center h-100" style="background-color: rgba(0, 0, 0, 0.8);">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-5 col-md-8">
          <form class="bg-white rounded-5 shadow-5-strong p-5" method="POST" action="<%= results_path %>">
            <% flash.each do |type, msg| %>
              <div class="alert alert-danger">
                <%= msg %>
              </div>
            <% end %>
            <div class="form-outline mb-4">
              <input type="text" name="address" class="form-control" />
              <label class="form-label" for="address">Enter your address or zip code </label>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Get your forecast</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lookup/results.html.erb
<style>
#intro {
  position: fixed;
  object-fit: cover;
  z-index: -1;
  right: 0;
  bottom: 0;
  min-width: 100vh;
  min-height: 100vh;
  height: 100vh;
}

#introContent {
  height: 100vh;
}

p {
  font-size: 1.1em;
  margin-top: 0.4em;
  margin-bottom: 0.4em;
  font-weight: 200;
}
</style>

<video autoplay muted loop id="intro">
  <source src="<%= image_path("AdobeStock_197523665.webm") %>" type="video/webm" />
</video>

<div id="introContent" class="bg-image shadow-2-strong">
  <div class="mask d-flex align-items-center h-100" style="background-color: rgba(0, 0, 0, 0.8);">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-9 col-md-8 bg-white rounded-5 shadow-5-strong">
          <div class="m-4 text-justify">
            <% if @cached_response %>
              <div class="col-12 position-relative">
                <span class="col-1 position-absolute top-0 end-0 badge badge-info">cached</span>
              </div>
            <% end -%>
            <h2 class="text-center">
              In <span class="badge badge-secondary"><%= params[:address] %></span>
              as of <span class="badge badge-info"><%= time_ago_in_words(Time.parse(@current[:asOf])) %> ago</span>,
              <br />
              it is <span class="badge badge-info"><%= time_of_day(@current[:daylight]) %></span>,
              and <span class="badge badge-primary"><%= @current[:conditionCode].titleize %></span> right now.</h2>
            <br />
            <div>
              <p> The temperature is <strong><%= @current[:temperature] %>&#8451;</strong>,
                but feels like <strong><%= @current[:temperatureApparent] %>&#8451;</strong>.</p>
              <p>Wind is blowing at <strong><%= @current[:windSpeed] %> kmph</strong>, gusting to <strong><%= @current[:windGust] %> kmph</strong>,
                in a <strong><%= direction_as_cardinal(@current[:windDirection]) %>erly direction</strong>.</p>
              <p>Currently, the relative humidity is at <strong><%= @current[:humidity] %></strong>,
                with a pressure of <strong><%= @current[:pressure] %> millibars</strong>.</p>
            </div>
            <h3 class="mt-3">What's Next?</h3>

            <table class="mt-3 table align-middle mb-0 bg-white">
              <thead class="table-light">
                <tr>
                  <th>Day</th>
                  <th>Cond.</th>
                  <th>temp min</th>
                  <th>temp max</th>
                  <th>precip amount</th>
                  <th>precip type</th>
                  <th>precip chance</th>
                </tr>
              </thead>
              <tbody>
                <% @nxt_days[0..6].each do |day| %>
                  <tr>
                    <td><%= Time.parse(day[:forecastStart]).strftime("%A") %></td>
                    <td><%= day[:conditionCode].titleize %></td>
                    <td><%= day[:temperatureMin].floor %>&#8451;</td>
                    <td><%= day[:temperatureMax].ceil %>&#8451;</td>
                    <td><%= day[:precipitationAmount]%> mm</td>
                    <td><%= day[:precipitationType] %></td>
                    <td><%= (day[:precipitationChance] * 100).to_i %>%</td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>